/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_cognito_identity_pool_id": "ap-southeast-1:db0e0c5b-1b3b-476e-a369-3e7eb0188fb4",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_PdK5F8gnS",
    "aws_user_pools_web_client_id": "3uqvoeh18tedhjdlkep98nv6ep",
    "oauth": {
        "domain": "trekking73950f92-73950f92-test.auth.ap-southeast-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://test.leonui.app/",
        "redirectSignOut": "https://test.leonui.app/",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_user_files_s3_bucket": "trekking0a3270a152dc4cb0b5ba6e3dcb75860775048-test",
    "aws_user_files_s3_bucket_region": "ap-southeast-1"
};


export default awsmobile;
