name: Deploy test leonui.app
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: build 
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}

