name: Deploy test test.leonui.app
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:
    inputs:
      body:
        default: ""
      test:
        default: "false"
  pull_request_target:
jobs:
    name: build 
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install -g yarn
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install yarn dependencies
      run: ls -a
