name: Deploy test leonui.app
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: build 
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install -g yarn
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install yarn dependencies
      run: yarn install --frozen-lockfile
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET }}
        aws-region: ap-southeast-1
