name: Deploy test test.leonui.app
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:
    inputs:
      body:
        default: ""
      test:
        default: "false"
  pull_request_target:
jobs:
  build:
    name: build 
    strategy:
      matrix:
        runs-on: [ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
    - name: Set Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install -g yarn
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install yarn dependencies
      run: yarn install --frozen-lockfile
    # - name : tesst dsdsd 
    #   run: ls -a
    # - name: Remove file serverless local
    #   run: mv serverless.yml serverless_tmp.yml
    - name: Copy file serverless
      run: cp ./serverless/serverless_test.yml ./serverless.yml
    - name : Deploy to aws serverless
      run: yarn run deploy
    
